### ISSUE TITLE
triplicate `already exists` warnings after successful download

### ISSUE THREAD

**Issue by katrinleinweber** [jonmcalder/exercism#2]
with R 3.4.0 & [e5d12480](https://github.com/jonmcalder/exercism/tree/e5d12480)

![exercism-r-pkg-next-triplicate-warnings-1](https://user-images.githubusercontent.com/9948149/27760097-826ce3b0-5e3f-11e7-99d5-185b12333d55.png)
![exercism-r-pkg-next-triplicate-warnings-2](https://user-images.githubusercontent.com/9948149/27760099-8545c6d8-5e3f-11e7-9549-f1b5c9195720.png)

**Comment by katrinleinweber** [comment]
Strangely, adding `showWarnings = FALSE` in [`api.R#L87`](https://github.com/jonmcalder/exercism/blob/master/R/api.R#L87), then `Rebuild & Reload` doesn't stop these.

**Comment by jonmcalder** [comment]
Thanks for picking this up! Not really sure how I missed it in the first place, but my automated test coverage is pretty limited so far, and clearly so was my manual testing in this case!

Anyway, I've identified the 🐛 so should be fixed in the next update 😃
